import { defineStadium, type StadiumSchema } from "@stadium/stadium-generator";
import {
    anchorsFromPairs,
    jointsFromPairs,
    line,
    pairedIndexes,
    pairList,
    pos,
    repeat,
    vLine,
} from "@stadium/utils";

export const legacyStadiumSchema = {
    name: "HaxFootball (Legacy)",
    canBeStored: false,
    width: 1090,
    height: 395,
    bg: {
        type: "grass",
        width: 930,
        height: 266,
    },
    goals: [
        {
            p0: [-1065, 0],
            p1: [-1005, 0],
            team: "blue",
        },
        {
            p0: [1006.9833374023, 1.6000061035156],
            p1: [1063.9833374023, 1.6000061035156],
            team: "red",
        },
    ],
    playerPhysics: {
        bCoef: 0.5,
        invMass: 1e26,
        kickStrength: 7,
    },
    ballPhysics: {
        radius: 7.125,
        bCoef: 0.5,
        cMask: ["red", "blue", "wall"],
        color: "631515",
        cGroup: ["ball", "kick", "score"],
    },
    cameraFollow: "player",
    spawnDistance: 980,
    traits: {},
    redSpawnPoints: [],
    blueSpawnPoints: [],
    rects: [
        {
            name: "fieldBounds",
            x: [-930, 930],
            y: [-266, 266],
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        },
    ],
    lines: [
        line({
            from: {
                x: 0,
                y: 334,
                vertex: { bCoef: 0.1, cMask: ["red", "blue"] },
            },
            to: {
                x: 0,
                y: -330,
                vertex: { bCoef: 0.1, cMask: ["red", "blue"] },
            },
            segment: {
                vis: false,
                bCoef: 0.1,
                cMask: ["red", "blue"],
                cGroup: [],
            },
            name: "midfieldCollision",
        }),
        vLine({
            x: -775,
            yStart: -375,
            yEnd: 375,
            segment: {
                vis: false,
                color: "ffea00",
                bCoef: 0.1,
                cMask: ["red", "blue"],
                cGroup: [],
            },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 775,
            yStart: -375,
            yEnd: 375,
            segment: {
                vis: false,
                color: "ffea00",
                bCoef: 0.1,
                cMask: ["red", "blue"],
                cGroup: [],
            },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -775,
            yStart: -266,
            yEnd: 266,
            segment: { color: "ffea00", cMask: [] },
            name: "leftGoalLine",
            vertex: { cMask: [] },
        }),
        vLine({
            x: -620,
            yStart: -266,
            yEnd: 266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -465,
            yStart: -266,
            yEnd: 266,
            segment: { color: "d0312d", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -310,
            yStart: -266,
            yEnd: 266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -155,
            yStart: -266,
            yEnd: 266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 155,
            yStart: -266,
            yEnd: 266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 310,
            yStart: -266,
            yEnd: 266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 465,
            yStart: -266,
            yEnd: 266,
            segment: { color: "d0312d", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 620,
            yStart: -266,
            yEnd: 266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 775,
            yStart: -266,
            yEnd: 266,
            segment: { color: "ffea00", cMask: [] },
            name: "rightGoalLine",
            vertex: { cMask: [] },
        }),
        vLine({
            x: 0,
            yStart: -266,
            yEnd: 266,
            segment: { color: "acde97", cMask: [] },
            name: "midfieldLine",
            vertex: { cMask: [] },
        }),
        vLine({
            x: -744,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -744,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -713,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -713,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -682,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -682,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -651,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -651,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -589,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -589,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -558,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -558,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -527,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -527,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -496,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -496,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -434,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -434,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -403,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -403,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -372,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -372,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -341,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -341,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -279,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -279,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -248,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -248,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -217,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -217,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -186,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -186,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -124,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -124,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -93,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -93,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -62,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -62,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -31,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -31,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 31,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 31,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 62,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 62,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 93,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 93,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 124,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 124,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 186,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 186,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 217,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 217,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 248,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 248,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 279,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 279,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 341,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 341,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 372,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 372,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 403,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 403,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 434,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 434,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 496,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 496,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 527,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 527,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 558,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 558,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 589,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 589,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 651,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 651,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 682,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 682,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 713,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 713,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 744,
            yStart: 80,
            yEnd: 60,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 744,
            yStart: -60,
            yEnd: -80,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -697.5,
            yStart: 266,
            yEnd: 241,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -697.5,
            yStart: -241,
            yEnd: -266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -542.5,
            yStart: 266,
            yEnd: 241,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -542.5,
            yStart: -241,
            yEnd: -266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -387.5,
            yStart: 266,
            yEnd: 241,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -387.5,
            yStart: -241,
            yEnd: -266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -232.5,
            yStart: 266,
            yEnd: 241,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -232.5,
            yStart: -241,
            yEnd: -266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -77.5,
            yStart: 266,
            yEnd: 241,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -77.5,
            yStart: -241,
            yEnd: -266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 77.5,
            yStart: 266,
            yEnd: 241,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 77.5,
            yStart: -241,
            yEnd: -266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 232.5,
            yStart: 266,
            yEnd: 241,
            segment: { color: "C7E6BD", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 232.5,
            yStart: -241,
            yEnd: -266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 387.5,
            yStart: 266,
            yEnd: 241,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 387.5,
            yStart: -241,
            yEnd: -266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 542.5,
            yStart: 266,
            yEnd: 241,
            segment: { color: "C7E6BD", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 542.5,
            yStart: -241,
            yEnd: -266,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 697.5,
            yStart: 266,
            yEnd: 241,
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 697.5,
            yStart: -241,
            yEnd: -266,
            segment: { color: "C7E6BD", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: -930,
            yStart: -60,
            yEnd: 60,
            segment: { color: "ffea00", cMask: [] },
            vertex: { cMask: [] },
        }),
        vLine({
            x: 930,
            yStart: -60,
            yEnd: 60,
            segment: { color: "ffea00", cMask: [] },
            vertex: { cMask: [] },
        }),
        line({
            from: { x: -930, y: -60, vertex: { cMask: [] } },
            to: { x: -980, y: -130, vertex: { cMask: [] } },
            segment: { color: "ffea00", cMask: [] },
        }),
        line({
            from: { x: -930, y: 60, vertex: { cMask: [] } },
            to: { x: -990, y: -10, vertex: { cMask: [] } },
            segment: { color: "ffea00", cMask: [] },
        }),
        line({
            from: { x: 930, y: -60, vertex: { cMask: [] } },
            to: { x: 980, y: -130, vertex: { cMask: [] } },
            segment: { color: "ffea00", cMask: [] },
        }),
        line({
            from: { x: 930, y: 60, vertex: { cMask: [] } },
            to: { x: 990, y: -10, vertex: { cMask: [] } },
            segment: { color: "ffea00", cMask: [] },
        }),
        vLine({
            x: -1005,
            yStart: 360,
            yEnd: -360,
            segment: { vis: false, color: "FF", cMask: ["ball"] },
        }),
        vLine({
            x: 1005,
            yStart: 360,
            yEnd: -360,
            segment: {
                vis: false,
                color: "d0312d",
                cMask: ["ball"],
            },
        }),
    ],
    planes: [
        {
            rect: { x: [-1065, 1065], y: [-350, 350] },
            side: "outside",
            props: { cMask: ["ball"] },
        },
        {
            rect: { x: [-1090, 1090], y: [-375, 375] },
            side: "outside",
            props: { bCoef: 0.9 },
        },
        {
            line: "leftGoalLine",
            side: "right",
            props: { cMask: ["c0"] },
        },
        {
            line: "rightGoalLine",
            side: "left",
            props: { cMask: ["c1"] },
        },
        {
            normal: [-1, 0],
            dist: 0,
            cMask: ["c2"],
        },
        {
            normal: [1, 0],
            dist: 0,
            cMask: ["c3"],
        },
    ],
    discs: [
        {
            radius: 4,
            invMass: 0,
            pos: pos(930, -60),
            color: "FFFF00",
        },
        {
            radius: 4,
            invMass: 0,
            pos: pos(-930, -60),
            color: "FFFF00",
        },
        {
            radius: 4,
            invMass: 0,
            pos: pos(-930, 60),
            color: "FFFF00",
        },
        {
            radius: 4,
            invMass: 0,
            pos: pos(930, 60),
            color: "FFFF00",
        },
        ...repeat(28, {
            radius: 0,
            invMass: 1,
            pos: pos(0, 0),
            color: "transparent",
            cGroup: [],
        }),
        ...repeat(4, {
            radius: 1,
            invMass: 1,
            pos: pos(9999, 9999),
            color: "FF0000",
            cGroup: [],
        }),
        ...repeat(12, {
            radius: 0,
            invMass: 1,
            pos: pos(0, 0),
            color: "transparent",
            cGroup: [],
        }),
        ...repeat(2, {
            radius: 1,
            invMass: 1,
            pos: pos(9999, 9999),
            color: "f5f5f5",
            cGroup: [],
        }),
        ...repeat(2, {
            radius: 7.125,
            invMass: 0,
            pos: pos(2000, 2000),
            color: "FFAA00",
            cGroup: [],
            cMask: [],
        }),
        ...repeat(3, {
            radius: 1,
            invMass: 1,
            pos: pos(9999, 9999),
            color: "f5f5f5",
            cGroup: [],
        }),
        ...repeat(4, {
            radius: 0,
            invMass: 1,
            pos: pos(0, 0),
            color: "transparent",
            cGroup: [],
        }),
    ],
    anchors: [
        ...anchorsFromPairs({ prefix: "orange", pairs: pairList([5, 6]) }),
        ...anchorsFromPairs({ prefix: "blue", pairs: pairList([7, 8]) }),
        ...anchorsFromPairs({ prefix: "ball", pairs: pairList([50, 51]) }),
        ...anchorsFromPairs({
            prefix: "red",
            pairs: pairedIndexes({ start: 9, count: 12 }),
        }),
        ...anchorsFromPairs({
            prefix: "white",
            pairs: pairedIndexes({ start: 37, count: 6 }),
        }),
        ...anchorsFromPairs({
            prefix: "tail",
            pairs: pairList([56, 57], [58, 59]),
        }),
    ],
    joints: [
        ...jointsFromPairs({
            prefix: "orange",
            pairs: pairList([5, 6]),
            color: "ff9912",
        }),
        ...jointsFromPairs({
            prefix: "blue",
            pairs: pairList([7, 8]),
            color: "3e67cf",
        }),
        ...jointsFromPairs({
            prefix: "ball",
            pairs: pairList([50, 51]),
            color: "FFAA00",
        }),
        ...jointsFromPairs({
            prefix: "red",
            pairs: pairedIndexes({ start: 9, count: 12 }),
            color: "FF0000",
        }),
        ...jointsFromPairs({
            prefix: "white",
            pairs: pairedIndexes({ start: 37, count: 6 }),
            color: "f5f5f5",
        }),
        ...jointsFromPairs({
            prefix: "tail",
            pairs: pairList([56, 57], [58, 59]),
            color: "f5f5f5",
        }),
    ],
} satisfies StadiumSchema;

export const { stadium: legacyStadium, index: legacyStadiumIndex } =
    defineStadium(legacyStadiumSchema);
